[workspace]
resolver = "2"
members = [
  "crates/node",
  "crates/runtime",
  "crates/pallets/starknet",
  "crates/primitives/starknet",
  "crates/primitives/digest-log",
  "crates/client/block-proposer",
  "crates/client/db",
  "crates/client/rpc-core",
  "crates/client/rpc",
  "crates/client/mapping-sync",
  "crates/client/storage",
  "crates/client/transaction-pool",
  "crates/client/deoxys",
  "crates/client/starknet_client",
]

[profile.release]
panic = "unwind"

[profile.production]
inherits = "release"
codegen-units = 1    # Setting this to 1 allows for more optimizations at the cost of slower compile time
lto = true           # Enables Link Time Optimization, enabling more aggressive optimizations across the entire codebase
opt-level = 3        # Optimize for speed regardless of binary size or compile time
rpath = false        # Disables adding rpath to the binary

[workspace.package]
authors = ["Abdelhamid Bakhta <@abdelhamidbakhta>"]
edition = "2021"
repository = "https://github.com/keep-starknet-strange/madara/"
version = "0.2.0"

[workspace.dependencies]
# Substrate frame dependencies
frame-executive = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
frame-system-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
frame-try-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }

# Substrate primitives dependencies
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-consensus-aura = { git = "http://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-consensus-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-offchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-version = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-database = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-storage = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-state-machine = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-trie = { version = "7.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }

# Substrate client dependencies
sc-client-db = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", features = [
  "rocksdb",
] }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-network-common = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-network-sync = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
# For integration tests in order to create blocks on demand
sc-consensus-manual-seal = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
sc-consensus-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-rpc-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-transaction-pool-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-block-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-proposer-metrics = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
substrate-test-runtime-client = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }


# Substrate build & tools dependencies
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
substrate-wasm-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }

# Substrate Frame pallet
pallet-aura = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
pallet-grandpa = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
pallet-timestamp = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }

# Madara pallets
pallet-starknet = { path = "crates/pallets/starknet", default-features = false }

# Madara primtitives
mp-starknet = { path = "crates/primitives/starknet", default-features = false }
mp-digest-log = { path = "crates/primitives/digest-log", default-features = false }

# Madara client
mc-mapping-sync = { path = "crates/client/mapping-sync" }
mc-db = { path = "crates/client/db" }
mc-storage = { path = "crates/client/storage" }
mc-rpc = { path = "crates/client/rpc" }
mc-rpc-core = { path = "crates/client/rpc-core" }
mc-block-proposer = { path = "crates/client/block-proposer" }
mc-transaction-pool = { path = "crates/client/transaction-pool" }
mc-data-availability = { path = "crates/client/data-availability" }

# Madara runtime
madara-runtime = { path = "crates/runtime" }

# Starknet dependencies
# Cairo Virtual Machine
cairo-vm = { git = "https://github.com/keep-starknet-strange/cairo-rs", branch = "no_std-support-21eff70", default-features = false, features = [
  "cairo-1-hints",
  "parity-scale-codec",
] }
starknet-crypto = { version = "0.6.0", default-features = false }
starknet-core = { version = "0.6.0", default-features = false }
starknet-ff = { version = "0.3.4", default-features = false }

blockifier = { git = "https://github.com/keep-starknet-strange/blockifier", branch = "no_std-support-7578442", default-features = false, features = [
  "parity-scale-codec",
] }
starknet_api = { git = "https://github.com/keep-starknet-strange/starknet-api", branch = "no_std-support-dc83f05", features = [
  "testing",
  "parity-scale-codec",
], default-features = false }

# Cairo lang
cairo-lang-starknet = { git = "https://github.com/keep-starknet-strange/cairo.git", branch = "no_std-support-8bbf530", default-features = false }
cairo-lang-casm-contract-class = { git = "https://github.com/keep-starknet-strange/cairo.git", branch = "no_std-support-8bbf530", default-features = false }
cairo-lang-casm = { git = "https://github.com/keep-starknet-strange/cairo.git", branch = "no_std-support-8bbf530", default-features = false }
cairo-lang-utils = { git = "https://github.com/keep-starknet-strange/cairo.git", branch = "no_std-support-8bbf530", default-features = false }

# Other third party dependencies
anyhow = "1.0.75"
flate2 = "1.0.27"
scale-codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false }
scale-info = { version = "2.9.0", default-features = false }
lazy_static = { version = "1.4.0", default-features = false }
log = { version = "0.4.20", default-features = false }
hex = { version = "0.4.3", default-features = false }
safe-mix = { version = "1.0", default-features = false }
jsonrpsee = { version = "0.16.3", default-features = false }
clap = { version = "4.4.2", default-features = false }
futures = { version = "0.3.28", default-features = false }
futures-timer = { version = "3.0.2", default-features = false }
reqwest = { version = "0.11.20", default-features = false }
serde = { version = "1.0.188", default-features = false }
serde_json = { version = "1.0.106", default-features = false }
serde_with = { version = "2.3.3", default-features = false }
bitvec = { version = "1", default-features = false }
thiserror = "1.0.48"
thiserror-no-std = "2.0.2"
derive_more = { version = "0.99.17", default-features = false }
rstest = "0.17.0"
pretty_assertions = "1.4.0"
linked-hash-map = { version = "0.5.6", default-features = false }
parking_lot = "0.12.1"
async-trait = "0.1.73"
indexmap = { git = "https://github.com/bluss/indexmap", rev = "ca5f848e10c31e80aeaad0720d14aa2f6dd6cfb1", default-features = false }
num-traits = "0.2.8"

# Deoxys
mc-deoxys = { path = "crates/client/deoxys" }
starknet_client = { path = "crates/client/starknet_client" }
pathfinder-common = { git = "https://github.com/KasarLabs/pathfinder", branch = "main"}
pathfinder = { git = "https://github.com/KasarLabs/pathfinder", branch = "main" }
pathfinder-retry = { git = "https://github.com/KasarLabs/pathfinder", branch = "main"}
pathfinder-serde = { git = "https://github.com/KasarLabs/pathfinder", branch = "main"}
stark_hash = { git = "https://github.com/KasarLabs/pathfinder", branch = "main"}
stark_poseidon = { git = "https://github.com/KasarLabs/pathfinder", branch = "main"}
tokio = "1.24.2"
assert_matches = "1.5.0"
starknet-gateway-types = { git = "https://github.com/KasarLabs/pathfinder", branch = "main"}
starknet-gateway-test-fixtures = { git = "https://github.com/KasarLabs/pathfinder", branch = "main"}
mockito = "0.31.0"
validator = "0.12"
enum-iterator = "1.4.1"
http = "0.2.8"
mockall = "0.11.2"
os_info = "3.6.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
tokio-retry = "0.3"
tracing = "0.1.37"
url = "2.2.2"
assert = "0.0.4"
itertools = "0.10.5"
strum_macros = "0.25.2"
tempfile = "3.3.0"
num-bigint = "0.4"
async-stream = "0.3.3"
axum = "0.6.12"
base64 = "0.13.0"
byteorder = "1.4.3"
camelpaste = "0.1.0"
chrono = "0.4.26"
const_format = "0.2.30"
ethers = "2.0.3"
futures-channel = "0.3.21"
futures-util = "0.3.21"
hyper = "0.14"
insta = "1.29.0"
integer-encoding = "3.0.4"
jsonschema = "0.17.0"
libmdbx = "0.3.5"
metrics = "0.21.0"
once_cell = "1.17.1"
paste = "1.0.9"
primitive-types = "0.12.1"
parity-scale-codec = "3.5.0"
prometheus-parse = "0.2.4"
regex = "1.9.0"
rustc-hex = "2.1.0"
schemars = "0.8.12"
serde_yaml = "0.9.16"
sha3 = "0.10.8"
simple_logger = "4.0.0"
strum = "0.25.0"
tokio-stream = "0.1.8"
tracing-subscriber = "0.3.16"
tower = "0.4"

